version: '3.3'

services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'qiuying'
    ports:
      - 2023:5432
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 2024:6379
    volumes:
      - ./data/redis-data:/data

  client:
    build: client
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 2025:80
    depends_on:
      - console

  console: 
    build: console
    working_dir: /console
    environment:
      MODE: 'prod'
    volumes:
      - ./data/console/data:/console/data
      - ./data/console/static:/console/static
    command: /bin/bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh -t 20 pg:5432 -- python main.py && gunicorn -w=4 main:app -b 0.0.0.0:5000 --access-logfile data/gunicorn.log"
    depends_on:
      - pg
